### ISSUE TITLE
Step Zero

### ISSUE THREAD

**Issue by aduishenov** [AndroidAkyl/Target-English#2]
So, I would prefer to use English as a common language. 
А так башка тилдер деле боло берет )) 
Just sayin. 
These are the questions that I am interested in:

1. what visions do we have?
2. what skills we have?
3. How are we going to collaborate?
4. What is each of us currently doing related to this project?

@AndroidAkyl  Your suggestions?

**Comment by AndroidAkyl** [comment]
Sub-zero prochital))

**Comment by AndroidAkyl** [comment]
**what visions do we have?**

- Building a play market platform for entrepreneurs, as I see it for now.

As I see, firstly we start building a simple web-application that allows us keep data in it, it will have to be a web-system, where users can insert, pull data, filter by statuses and etc.. this will need to be drawn I feel, for better explanation. The system will also have to be useful for accounting purposes, it needs to calculate income, commission, salaries, maybe even tax pay offs. Basically I want the system to replace 1C in the near future, and that is only its small usage. The system then will be connecting different entrepreneurs, business people, freelancers of the KGZ and then the World wide. 

**what skills we have?**

As I see, we are 2 project managers who are trying to build something. In my case, I have stopped coding since long ago and am not planning to get it started again, but I have a couple of more solutions for it. I have good programmer friends who might be interested in working such a project, also we have Hyzeyfe, who is a developer for StrongBrain, and btw this project will also be under StrongBrain's coverage.  Meaning StrongBrain runs it. 
So we also have Huzeyfe's skills and they are : 
- java
- javascript
- android apps
- database set up 
- web skills: python, html5 
But, since StrongBrain is launching 3 other projects this summer Huzeyfe will be pretty loaded and we cant really hope to get him any time soon.  So we need to think about getting some other developers if we want to start it off, but I dont think we need to care about this for now, since we haven't even put the MVP idea on paper. 

**How are we going to collaborate?**
The collaboration I feel should firstly start on needs, plans and visions. 
For now, the github.com will be our main collaboration platform. Lets think about this some more though.

**What is each of us currently doing related to this project?**

Well, in my case I am trying to launch the Target School, the initial simple system that we will build, going to be used for our Schools firstly, each of us, will use the system for our schools, basically we will be testing it and improving it until it gets to the point its crafted enough to franchise it. 

This is a brief of my vision and please put yours here too, so we can then talk the details out.

**Comment by aduishenov** [comment]
1. What vision do we have?

My vision is based on the idea that meritocracy is the best way/principle in achieving your goals. Hence, the only real value is a set of skills and evolving knowledge. Everyone should be able to participate in projects and/or clubs to develop a certain set of skills and gain knowledge. 

2. What skills do we have?

Basically project management, business analyst, educator, animation/design. My main pursuit at the moment is educator/project manager.

3. How are we going to collaborate?

Since we need MVP first, it should be our first project. After we decide on user stories generated both by us and user feedback (current and based on short surveys). I would suggest using [Trello](https://trello.com/) though, which is more versatile. But I am ready to go on either of them. 

4. What is each of us currently doing related to this project?

Currently, I am teaching English at "Colludium" skill center. The aim of the "Colluduim" is to develop and implement a curriculum where students will be able to develop "21st-century skills" and acquire knowledge through project-based learning method. 

Sorry for the delay @AndroidAkyl

**Comment by AndroidAkyl** [comment]
@aduishenov Ok.

Regarding the Trello, honestly, I dont see it being any better than github.com. 
- Can you pls explain a bit more on : 

" Since we need MVP first, it should be our first project. After we decide on user stories generated both by us and user feedback (current and based on short surveys). "

**Comment by aduishenov** [comment]
> Since we need MVP first, it should be our first project. After we decide on user stories generated both by us and user feedback (current and based on short surveys).

I mean that MVP (whatever it will be) should be the first project that we can start working on. Apparently, you started working with groups of people teaching them English and so do I. These groups of people can be used as a source for ideas on what the MVP should include.
You and I also should include our own ideas into MVP. So, those ideas should be reflected in the project as "user stories". 
If we need extra information we can survey those groups of students and get the data we need to build the scaffolding for the MVP.

**Comment by AndroidAkyl** [comment]
Awesome, lets do it.

**Comment by aduishenov** [comment]
MVP for languages online school management system

MVP User Requirements

As an admin, I should be able to make online enrollings to the school system. 
As an admin, I should be able to add different account types with different permissions. 
As an admin, I should be able to vote.

As a system user, I should be able to get access to the system by creating an account. 
As a system user, I should be able to request access to system services and programs. 
As a system user, I should be able to vote. 

MVP Design requirements

The system should be able to host a database of data. 
The system should enable the users to create an online account, use system tools, access data, exchange data, delete own data, terminate account. 
The system should enable the user to have a voting mechanism. 

System processes description

After creating an account users should be able to view, edit items with appropriate permission. 
Users should be able to create  content cards, rate cards, assign cards, assign customizable labels to cards, vote cards, bundle cards, change permissions on the card. 
System should be able to provide row statistics to be able to make informed decisions, such as:
- estimation points;
- feedback information;
- voting results. 
System should function as a web-based software service. 
The main function of the system is to provide mechanisms for interaction management and use external tools to manage content. It should be used as a reference and guidance tool along with the management, sales, marketing and promotion processes and procedures in place. 

(images will be attached later)
